default:
  tags:
    - nix

variables:
  NIX_BUILD_FLAGS: "--no-update-lock-file --print-build-logs --show-trace"

before_script:
  - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@drf-gitlab.cea.fr".insteadOf "ssh://git@drf-gitlab.cea.fr"
  - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@drf-gitlab.cea.fr/".insteadOf "git@drf-gitlab.cea.fr:"

build:
  stage: build
  script:
    - nix build $NIX_BUILD_FLAGS

test:
  stage: test
  script:
    - nix flake check $NIX_BUILD_FLAGS
  dependencies: []

manpage:
  stage: deploy
  script:
    - nix build $NIX_BUILD_FLAGS '.#manpage'
    - cp -Lr ./result manpage
  artifacts:
    name: "manpage-$CI_COMMIT_REF_SLUG"
    paths:
      - manpage

pages:
  stage: deploy
  script:
    - nix build $NIX_BUILD_FLAGS '.#mdbook'
    - cp -Lr ./result public
  artifacts:
    name: "mdbook"
    paths:
      - public
  dependencies: []
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
