# See https://docs.readthedocs.com/platform/stable/config-file/v2.html

version: "2"

build:
  os: "ubuntu-lts-latest"
  tools:
    python: "3.14"
  apt_packages:
    - curl
    - proot
    - make
    - plantuml
    - graphviz
  jobs:
    pre_build:
      - curl -L https://github.com/DavHau/nix-portable/releases/latest/download/nix-portable-$(uname -m) > ./nix-portable
      - chmod +x ./nix-portable
      - ./nix-portable nix build --print-build-logs .#docs.NIXDOMAIN_OBJECTS

      # This line assumes the variable `NIXDOMAIN_OBJECTS="/tmp/nix-objects.json"`
      # was configured in the ReadTheDocs project settings
      - ./nix-portable nix store cat $(readlink result) > /tmp/nix-objects.json

      - curl -LO "https://github.com/typst/typst/releases/latest/download/typst-x86_64-unknown-linux-musl.tar.xz" --output-dir /tmp
      - tar -C /tmp -xf /tmp/typst-x86_64-unknown-linux-musl.tar.xz
    build:
      html:
        - make -C docs html "BUILDDIR=$READTHEDOCS_OUTPUT" TYPST=/tmp/typst-x86_64-unknown-linux-musl/typst

python:
  install:
    - requirements: docs/requirements.txt

sphinx:
  configuration: docs/conf.py
