version: "2"

build:
  os: "ubuntu-24.04"
  tools:
    python: "3.14"
  apt_packages:
    - curl
    - proot
    - plantuml
  jobs:
    pre_build:
      - curl -L https://github.com/DavHau/nix-portable/releases/latest/download/nix-portable-$(uname -m) > ./nix-portable
      - chmod +x ./nix-portable
      - ./nix-portable nix build --print-build-logs .#docs.NIXDOMAIN_OBJECTS

      # This line assumes the variable `NIXDOMAIN_OBJECTS="/tmp/nix-objects.json"`
      # was configured in the ReadTheDocs project settings
      - ./nix-portable nix store cat $(readlink result) > /tmp/nix-objects.json

python:
  install:
    - requirements: docs/requirements.txt

sphinx:
  configuration: docs/conf.py
