# EPICS IOC
org.phoebus.pv.ca/addr_list=localhost
org.phoebus.pv.ca/auto_addr_list=false

# Archiver Appliance
org.csstudio.trends.databrowser3/urls=pbraw://localhost:8080/retrieval
org.csstudio.trends.databrowser3/archives=pbraw://localhost:8080/retrieval

# Phoebus alarm
org.phoebus.applications.alarm/server=localhost:9092
org.phoebus.applications.alarm.logging.ui/service_uri=http://localhost:8081

# Phoebus save-and-restore
org.phoebus.applications.saveandrestore.client/jmasar.service.url=http://localhost:8082/save-restore

# Phoebus Olog
org.phoebus.olog.es.api/olog_url=http://localhost:8083
org.phoebus.olog.es.api/username=admin
org.phoebus.olog.es.api/password=adminPass
org.phoebus.logbook/logbook_factory=olog-es

# ChannelFinder
org.phoebus.channelfinder/serviceURL = http://localhost:8084/ChannelFinder
org.phoebus.channelfinder/username = admin
org.phoebus.channelfinder/password = adminPass
