[
  ./modules/archiver-appliance.nix
  ./modules/ca-gateway.nix
  ./modules/channel-finder/recceiver.nix
  ./modules/channel-finder/service.nix
  ./modules/phoebus/alarm-logger.nix
  ./modules/phoebus/alarm-server.nix
  ./modules/phoebus/scan-server.nix
  ./modules/phoebus/olog.nix
  ./modules/phoebus/save-and-restore.nix
]
