[
  ./modules/archiver-appliance.nix
  ./modules/ca-gateway.nix
  ./modules/channel-finder/recceiver.nix
  ./modules/channel-finder/service.nix
  ./modules/epics-environment.nix
  ./modules/iocs.nix
  ./modules/phoebus/alarm-logger.nix
  ./modules/phoebus/alarm-server.nix
  ./modules/phoebus/client.nix
  ./modules/phoebus/olog.nix
  ./modules/phoebus/save-and-restore.nix
]
