name: "Book GitHub Pages"

on:
  # Allows running this workflow manually
  workflow_dispatch:
  push:
    # The book must be built from only the master branch,
    # in order to have a single file that defines the build,
    # and not 3+ 'book-gh-pages.yml' files on each branch which must be the same.
    branches: [master]

permissions:
  contents: read

# Only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    if: "github.repository_owner == 'epics-extensions'"

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - uses: nixbuild/nix-quick-install-action@2c9db80fb984ceb1bcaa77cdda3fdf8cfba92035 # v34
      - uses: nix-community/cache-nix-action@7df957e333c1e5da7721f60227dbba6d06080569 # v7.0.2
        with:
          primary-key: build-docs-${{ hashFiles('.github/workflows/book-gh-pages.yml', 'flake.lock') }}
          purge: true
          purge-last-accessed: 2629800 # 1 month
          purge-prefixes: build-docs-
          purge-primary-key: never

      - name: "Build documentation books"
        run: |
          nix run --print-build-logs '.#ci-scripts/build-docs-multiversion'

      - name: Setup Pages
        uses: actions/configure-pages@45bfe0192ca1faeb007ade9deae92b16b8254a0d # v6.0.0
      - name: Upload artifact
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5.0.0
        with:
          path: './outputs/out/book'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5.0.0
