name: "Check EditorConfig"

permissions:
  contents: read

on:
  pull_request:

jobs:
  editorconfig:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        persist-credentials: false
    - uses: nixbuild/nix-quick-install-action@9f63be77f412a248c9d9a65a4c82cf066cdf8f0c # v35
    - name: "Check EditorConfig"
      run: |
        nix run 'nixpkgs#editorconfig-checker' --inputs-from . -- -format github-actions -no-color
